name: not_red_sound
description: "PPC"
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ">=3.2.0 <4.0.0"  

dependencies:
  flutter:
    sdk: flutter
  
  # MIDI обработка
  midi_util: ^1.0.2
  flutter_midi_engine: ^0.1.2
  
  # Экспорт и шаринг файлов
  share_plus: ^10.1.4
  archive: ^3.4.10
  
  # Для работы с файловой системой
  permission_handler: ^11.3.1
  
  # Аудио воспроизведение (опционально)
  flutter_sound: 9.30.0
  audio_session: 0.2.3  


  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/splash_icon.jpg"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/background.jpg
    - assets/electro_background.jpg
    - assets/rock_background.jpg
    - assets/background_dark.jpg
    - assets/sounds/Arachno_SoundFont_Version_1.0.sf2
    - assets/presets/notred_project_classic.json
    - assets/splash_icon.png
    - assets/splash_icon.jpg
